on: 
  push:
    branches:
    - master
name: Deploy
jobs:
  deployOnPush:
    name: deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: deploy to now
      uses: actions/zeit-now@master
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: --public --no-clipboard deploy ./site > $HOME/deploy.txt
    - name: alias deploy domain
      uses: actions/zeit-now@master
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: alias `cat $HOME/deploy.txt`
    - name: remove older deployments
      uses: actions/zeit-now@master
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: rm --safe --yes octokit-routes-openapi
