on:
  release:
    types: [published]
  repository_dispatch:
    types: [debug-notify-users]

name: Notify users
jobs:
  notify:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: node bin/notify-users
        env:
          PRIVATE_KEY: ${{ secrets.OCTOKIT_ROUTES_APP_PRIVATE_KEY }}
        with:
          event_type: octokit-routes-release-debug
          version: "v1.2.3"
          # version: ${{ github.event.release.tag_name }}
