on:
  push:
    branches:
      - master
      - beta
name: Release
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run build
      - uses: codfish/semantic-release-action@master
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # The `notify-users.yml` action is not executed because the release
      # is created by an action.
      - run: node bin/notify-users
        if: steps.semantic-release.outputs.new-release-published == 'true'
        env:
          PRIVATE_KEY: ${{ secrets.OCTOKIT_ROUTES_APP_PRIVATE_KEY }}
          INPUT_EVENT_TYPE: octokit-routes-release
          # simulating the v1.2.3 tag_name, hoping we get to work the `notify-users.yml` to work again
          INPUT_VERSION: ${{ join('v', steps.semantic-release.outputs.release-version) }}
