on:
  push:
    branches:
      - master
      - beta
name: Release
# These are recommended by the semantic-release docs: https://github.com/semantic-release/npm#npm-provenance
permissions:
    contents: write # to be able to publish a GitHub release
    issues: write # to be able to comment on released issues
    pull-requests: write # to be able to comment on released pull requests
    id-token: write # to enable use of OIDC for npm provenance

jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run build
      - run: ls dist/
      - run: npx semantic-release --debug
        env:
          # we use a Personal Access Token instead of the provided
          # GITHUB_TOKEN in order to get the release.yml workflow triggered
          GITHUB_TOKEN: ${{ secrets.OCTOKITBOT_PAT_FOR_SEMANTIC_RELEASE }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
